spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_uno
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080